/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jodicelukeendicott.riskofrain2database;

import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author lukej
 */
public class ItemRenderer extends javax.swing.JPanel implements ListCellRenderer<GameItem>{
    private JList<GameItem> itemList;
    private DefaultListModel<GameItem> dlm;
    /**
     * Creates new form ItemRenderer
     */
    public ItemRenderer() {
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabIcon = new javax.swing.JLabel();
        jLabRarity = new javax.swing.JLabel();
        jLabName = new javax.swing.JLabel();
        jLabDescrp = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabRarity.setText("Rarity:");

        jLabName.setText("Name:");

        jLabDescrp.setText("Description:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabName)
                    .addComponent(jLabRarity)
                    .addComponent(jLabDescrp))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabRarity)
                        .addGap(18, 18, 18)
                        .addComponent(jLabDescrp))
                    .addComponent(jLabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabDescrp;
    private javax.swing.JLabel jLabIcon;
    private javax.swing.JLabel jLabName;
    private javax.swing.JLabel jLabRarity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
public Component getListCellRendererComponent(JList<? extends GameItem> list, GameItem value, int index, boolean isSelected, boolean cellHasFocus){
jLabRarity.setText("Rarity:"+value.getRarity());
jLabName.setText("Name:"+value.getName());
jLabDescrp.setText("Description"+value.getEffect());
if(isSelected){
    setBackground(java.awt.Color.DARK_GRAY);
}
else{
    setBackground(java.awt.Color.LIGHT_GRAY);
}
jLabIcon.setIcon(value.getIcon());
    
    return this;
}
}
