/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jodicelukeendicott.riskofrain2database;

import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author lukej
 */
public class ItemRenderer extends javax.swing.JPanel implements ListCellRenderer<GameItem>{
    /**
     * Creates new form ItemRenderer
     */
    public ItemRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabIcon = new javax.swing.JLabel();
        jLabDescrp = new javax.swing.JLabel();
        jlabRarPerm = new javax.swing.JLabel();
        jLabRarity = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabIcon.setText("jLabel2");

        jLabDescrp.setText("jLabel3");

        jlabRarPerm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabRarPerm.setText("Rarity:");

        jLabRarity.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabDescrp, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabRarPerm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabRarity)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabRarPerm)
                            .addComponent(jLabRarity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabDescrp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabDescrp;
    private javax.swing.JLabel jLabIcon;
    private javax.swing.JLabel jLabRarity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlabRarPerm;
    // End of variables declaration//GEN-END:variables
@Override
public Component getListCellRendererComponent(JList<? extends GameItem> list, GameItem value, int index, boolean isSelected, boolean cellHasFocus){
jLabRarity.setText(value.getRarity());
jLabDescrp.setText(value.getEffect());
if(isSelected){
    setBackground(java.awt.Color.DARK_GRAY);
}
else{
    setBackground(java.awt.Color.LIGHT_GRAY);
}
jLabIcon.setIcon(value.getIcon());
    
    return this;
}
}
