/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jodicelukeendicott.riskofrain2database;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static jodicelukeendicott.riskofrain2database.Main.mmw;

/**
 *
 * @author lukej
 */
public class RunLogWin extends javax.swing.JFrame {
   private DefaultListModel<RunLogEntry> runlogdlm;
   public ArrayList<RunLogEntry> runs;
   private int idx = -1;
   WriteFiles wf;
   ReadFiles rf;
    /**
     * Creates new form RunLogWin
     */
    public RunLogWin() {
      /*  try {
           rf = new ReadFiles();
            wf = new WriteFiles();
           } catch (FileNotFoundException ex) {
               Logger.getLogger(RunLogWin.class.getName()).log(Level.SEVERE, null, ex);
           }
        */
          
           
        runs = new ArrayList<>();
        runlogdlm = new DefaultListModel<>();
        initComponents();
      //  rf.readJsonRun(runlogdlm);
        jbtnViewLog.setEnabled(false);
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jbtnViewLog = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuToJson = new javax.swing.JMenuItem();
        menuTotxt = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menunewentry = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menutoenemy = new javax.swing.JMenuItem();
        menutosurv = new javax.swing.JMenuItem();
        menutoitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(runlogdlm);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jbtnViewLog.setText("View Log");
        jbtnViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViewLogActionPerformed(evt);
            }
        });

        jButton2.setText("Add Log Entry");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back to Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenu2.setText("Export As..");

        menuToJson.setText(".Json File");
        menuToJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuToJsonActionPerformed(evt);
            }
        });
        jMenu2.add(menuToJson);

        menuTotxt.setText(".txt File");
        menuTotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTotxtActionPerformed(evt);
            }
        });
        jMenu2.add(menuTotxt);

        jMenu1.add(jMenu2);

        jMenu5.setText("New");

        menunewentry.setText("Log Entry");
        menunewentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menunewentryActionPerformed(evt);
            }
        });
        jMenu5.add(menunewentry);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Navigate");

        jMenu4.setText("Go To");

        menutoenemy.setText("Enemy Database");
        menutoenemy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutoenemyActionPerformed(evt);
            }
        });
        jMenu4.add(menutoenemy);

        menutosurv.setText("Survivor Database");
        menutosurv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutosurvActionPerformed(evt);
            }
        });
        jMenu4.add(menutosurv);

        menutoitem.setText("Item Database");
        menutoitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutoitemActionPerformed(evt);
            }
        });
        jMenu4.add(menutoitem);

        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnViewLog, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnViewLog, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        RunLogAddWin rlaw= new RunLogAddWin(runlogdlm, this);
        rlaw.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      this.setVisible(false);
      mmw.setVisible(true);
     // wf.saveRuns(runlogdlm);
      //Write information from this to a JSON File
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtnViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViewLogActionPerformed
       RunLogViewWin viewwin = new RunLogViewWin(runlogdlm.get(idx));
       viewwin.setVisible(true);
    }//GEN-LAST:event_jbtnViewLogActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
    if(evt.getValueIsAdjusting()){
       idx = evt.getLastIndex();
        jbtnViewLog.setEnabled(true);
   }
    }//GEN-LAST:event_jList1ValueChanged

    private void menuToJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToJsonActionPerformed
      if(runlogdlm.size()==0){
         JOptionPane.showMessageDialog(null, "There is nothing to export");
      }
      else{
        WriteFiles.printRun(runlogdlm,1);
      }
    }//GEN-LAST:event_menuToJsonActionPerformed

    private void menunewentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menunewentryActionPerformed
        this.setVisible(false);
        RunLogAddWin rlaw= new RunLogAddWin(runlogdlm, this);
        rlaw.setVisible(true);
    }//GEN-LAST:event_menunewentryActionPerformed

    private void menuTotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTotxtActionPerformed
  if(runlogdlm.size()==0){
         JOptionPane.showMessageDialog(null, "There is nothing to export");
      }
      else{
        WriteFiles.printRun(runlogdlm,2);
      }
    }//GEN-LAST:event_menuTotxtActionPerformed

    private void menutoenemyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutoenemyActionPerformed
        this.setVisible(false);
        EnemySelectionWin enwin = new EnemySelectionWin();
        enwin.setVisible(true);
    }//GEN-LAST:event_menutoenemyActionPerformed

    private void menutosurvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutosurvActionPerformed
        this.setVisible(false);
        SurvivorSelectionWin survwin = new SurvivorSelectionWin();
        survwin.setVisible(true);
    }//GEN-LAST:event_menutosurvActionPerformed

    private void menutoitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutoitemActionPerformed
        this.setVisible(false);
        GameItemSelectionWin itmwin = new GameItemSelectionWin();
        itmwin.setVisible(true);
    }//GEN-LAST:event_menutoitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunLogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunLogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunLogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunLogWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RunLogWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<RunLogEntry> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnViewLog;
    private javax.swing.JMenuItem menuToJson;
    private javax.swing.JMenuItem menuTotxt;
    private javax.swing.JMenuItem menunewentry;
    private javax.swing.JMenuItem menutoenemy;
    private javax.swing.JMenuItem menutoitem;
    private javax.swing.JMenuItem menutosurv;
    // End of variables declaration//GEN-END:variables
}
